### ISSUE TITLE
rationalise naming for meta data infrastructure

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#12]
Great job so far, but I was thinking the naming might be rationalised more. We have different names and plurial / singular, e.g.:

- `get_var` *vs* `set_vars` (see issue #11). 
- `get_meta` but `epivars()`

The following is merely a proposal. We could settle for the term `epivar` to refer to a standard epidemiological data field stored in a `dictionary`. An implementation could be:

### dictionary functions

- [x] `default_dictionary()`: returns the default dictionary
- [x] `get_dictionary()`: i.e. list the current epivar dictionary
- [x] `set_dictionary()`: i.e. set the current epivar dictionary; if arguments are empty, set the defaults

### epivars functions
i.e. interacting with a `linelist` object

- [x] `list_epivars()`: equivalent of the current `get_meta`, show epivars in a dataset; should have an option to return a simple vector of `character` which can be matched against inputs of `get_epivars()` and `set_epivars()`
- [x] `get_epivars()`: return one or more epivars from a dataset, the #11 version of `get_var()`
- [x] `set_epivars()`: set epivars in a dataset
- [ ] `add_epivars()`: add columns to a `linelist` as `epivars` (i.e. `merge` and `set_epivars`)
- [ ] `remove_epivars()`: remove columns to a `linelist` as `epivars` (i.e. `merge` and `set_epivars`)

**Comment by thibautjombart** [comment]
As of a57d87ce71931f1d2825b8f977572a0aa7a69bcc we have all of the above except for: 

- [ ] `add_epivars()`: add columns to a `linelist` as `epivars` (i.e. `merge` and `set_epivars`)
- [ ] `remove_epivars()`: remove columns to a `linelist` as `epivars` (i.e. `merge` and `set_epivars`)

**Comment by zkamvar** [comment]
Semantically, I think the `_dictionary` and `_epivars` functions should be switched like so:

### epivar functions

These functions act on the global epivars recognised by linelist:

 - `get_epivars()` returns what's currently defined in `getOptions("linelist_epivars")`
 - `set_epivars()` adds the epivars to the global epivars
 - `reset_epivars()` resets
 - `default_epivars()` shows the default epivars

### dictionary functions

These functions will act on the linelist object to return the definitions of epivars defined, but not the variables. These would be used for looking up column names. 

 -  `get_dictionary(x)` would be the equivalent of `list_epivars()/get_meta()`
 -  `lookup(x, ...)` would return the column/columns that are defined by the epivars stored in the object
 - `define(x, ...)/define(x, y) <- z` would allow users to define/redefine/remove epivars

### column functions

These are the functions that the users would use to access columns of the linelist. I'm not 

 - `get_cols(x, ..., simplify = TRUE)` would be the `get_epivars()/get_vars()` equivalent. This could be an individual step in a dplyr pipeline like so:

```r
ll %>% 
  group_by(!!lookup(., case)) %>%
  summarize(incidence = list(incidence(get_cols(., date_onset), group = get_cols(., age_group)) 
```

**Comment by zkamvar** [comment]
Verdict:

Structure of linelist object will change, so my comment is defunkt!

**Comment by zkamvar** [comment]
I'm closing this and moving its contents to #18
