### ISSUE TITLE
Restructure linelist class: make dictionary completely global

### ISSUE THREAD

**Issue by zkamvar** [reconhub/linelist#18]
Right now, linelist needs two things:

1. A global vector of epivars stored in `getOptions("linelist_epivars")`
2. An "epivars" attribute that stores
  - `$vars`, which is a list whose names are a subset of the global epivars and whose values are the columns of the linelist
  - `$meta` which is metadata about each variable in the data frame, 

The function `list_epivars(x)` returns a data dictionary specific to the linlist called "x", which is `$meta` with `$vars` merged in.

@thibautjombart has pointed out that it makes more sense for the dictionary to be global and to only store the key/value pairs with the linelist object itself. 

The global dictionary would look something like this and would be stored in `getOptions("linelist_dictionary")`:

|epivar|hxl|values | description|
|----|----|----|----|
| id | #respondee | | Anonymized identifier of patient |
| geo | #geo +lon +lat | | geographic coordinate of hospital |
| date_onset | #indicator +start | | reported date of symptom onset |
| case_definition | #indicator +name | probable, suspected | case definition |
|...|...|...|

The only necessary component of this would be the epivar so that it can be used for validation. This can be constructed manually, but the preferred method would be to import it from a pre-defined data frame potentially like so:

```r
library('linelist')
library('here')
set_dictionary(file = here('data', 'dictionary.csv'))
# set_dictionary(file = here('data', 'linelist.xlsx'), sheet = 2) # or if the data are in excel
```

From there, the data can be imported and the dictionary variables assigned

```r
ll <- rio::import(here('data', 'linelist.xlsx')
ll_old <- ll
ll <- clean_data(ll)
ll <- as_linelist(ll,
  "id" = "patient",
  "geo" = c("longitude", "latitude"),
  "date_onset" = "onset"
)
```

One cool trick would be a function that would give the user a template printed to their console:

```r
> epivar_template(ll)
ll <- as_linelist(ll,
  "id"         =    ,
  "geo"        =    ,
  "date_onset" = 
)
```

This way, with the \#hxl and values assigned, we can use that as a rudimentary validator to report to the user if their linelist doesn't match. 

Data export should be something to look into. Annick had mentioned that the ability to export with standardized columns would be nice, but this gets complicated with dual-acting vars like `geo`

--------------------

One of the challenging things is the question of naming conventions (see #12). The current scheme of `*_dictionary()` for the global dictionary makes sense, but the question remains: What do you call the function that returns the local definition of an epivar vs the function that returns the column/columns of an epivar?

Addition

# Roadmap

 - [x] change structure of linelist to have a global dictionary
 - [x] create import function to read in the dictionary. I would recommend using `rio::import` for this.
 - [x] function to look up column name from epivar definiton
 - [x] function to template epivars
 - [ ] validation against hxl or vars
 - [x] solidify naming scheme

I may be forgetting things, but this is what I came up with.

One strategy for this would be to **write the tests first**. This way, they will slowly get better and there will be fewer surprises as we change things.

**Comment by thibautjombart** [comment]
See changes with this PR https://github.com/reconhub/linelist/pull/19


### Changes

- dictionary is now part of the global options
- dictionary is a `data.frame` with 3 columns: `epivar`, `hxl`, and `description`
- default dictionary is a `.txt` file in `inst/`
- `linelist` now only contains a list of columns named after the *epivars*, so that `attr(x, "epivars")` is now what used to be `attr(x, "epivars")$vars`; the old `attr(x, "epivars")$meta` has been removed
- `list_epivars()` now lists content using the global dictionary
- `get_epivars()` by default returns all *epivars* in an object
- new functions `add_epivars()` and `set_epivars()` replace previous implementations

### TODO

I left  a bunch of `TODO` tags in the code, but essentially:

- there is no/little checking of `...` arguments when playing with *epivars*
- processing `...` has been simplified, but a missing feature is the ability to mix ways columns are specified; not sure if we want this, but `get_epivars(x, 1, "gender")` 
- the interface to change the dictionary is bare-bone
- tons of tests needed overall, especially for meaningful errors

**Comment by zkamvar** [comment]
This is fantastic! 

> there is no/little checking of ... arguments when playing with epivars

Yup, that usually happens when you remove all the validation code 🙈 

> processing ... has been simplified, but a missing feature is the ability to mix ways columns are specified; not sure if we want this, but get_epivars(x, 1, "gender")

See https://github.com/reconhub/linelist/pull/19#issuecomment-457440605

### Changes

I've generally added more tests here and stabilized some things. Processing `...` now passes the `list(...)` through `valid_dots()`, which returns a list. 

 - #20: the column order of the user's data frame is respected (except in cases of double-columned epivars). New (internal) funs: `order_epivars()`, `reset_epivars()`.
 - #21: validators are reinstated with nicer comments so that it's easier to see what's going on. All epivar manipulation for a linelist goes through `set_epivars()`, which has linelist methods and data.frame methods
 - #22: cleanup; `all_dictionary` argument in `list_epivars()` was changed to `full_dict`
 - #23: Add `rio::import()` and tests to `set_dictionary()`
 - #24: Add linelist templater function.

### TODO

 - `update_dictionary()` needs to do a basic `rbind`, but throw an error if it doesn't make sense
 - `export_dictionary()` should use `rio::export()` to write a dictionary to whatever file format
 - `set_dictionary()` should be able to take in names of columns to be the epivar, hxl, and comment columns
 - MOAR TESTS

**Comment by thibautjombart** [comment]
Definitely MOAR tests! 

New version looks really good. To write what was discussed on the phone: decision is to only refer to *epivars* via their names. Numbers or logicals are no longer going to be used as there would be possible confusion as to what the reference is: the output of `list_epivars`, of `get_dictionary`, or of the `data.frame`. 

I am adding a new issue for the printing. Made a very basic printing method for `linelist` objects, but having a version with subheaders is likely hard - see https://github.com/reconhub/linelist/issues/25


### UPDATED TODO

 - [x] `update_dictionary()` needs to do a basic `rbind`, but throw an error if it doesn't make sense
 - [ ] `export_dictionary()` should use `rio::export()` to write a dictionary to whatever file format
 - [x] `set_dictionary()` should be able to take in names of columns to be the epivar, hxl, and comment columns
- [x] `print.linelist()` check current printing, see if we can improve it to what was suggested in issue https://github.com/reconhub/linelist/issues/25
- [ ] **testing**: achieve full coverage
- [x] **documentation**: check all manpages, make sure descriptions are correct, that all have examples, update the vignette, check that the README is up to date

**Comment by zkamvar** [comment]
closing this issue as invalid because we no longer have a dictionary for linelist
