### ISSUE TITLE
Prepare for version 0.1 release

### ISSUE THREAD

**Issue by zkamvar** [reconhub/linelist#83]
This is a placeholder for the tasks that need to be completed for linelist to achieve version 0.1 status:

 - [ ] Highlight main features in the vignette (issue https://github.com/reconhub/linelist/issues/104)
 - [ ] Update README (issue https://github.com/reconhub/linelist/issues/104)
 - [ ] Audit imported packages
 - [ ] Check documentation
 - [ ] Boost tests to 100%
 - [ ] Investigate using anydate or parsedate for dates instead of lubridate (issue https://github.com/reconhub/linelist/issues/85)
 - [ ] Split standalone functionalities into their own package
    - [x] `clean_variable_spelling()`
    - [ ] `clean_dates()`
 - [ ] Move `epitrix::clean_variables()` to linelist and re-export in epitrix

**Comment by thibautjombart** [comment]
I will create a project to list issues which should ideally be addressed for the release of 0.1.0
Feel free to de-allocate issues if they seem too ambitious. At this stage we should aim for a minimal viable product rather than implement new features.

**Comment by zkamvar** [comment]
What is your expected release date?
